### ISSUE TITLE
Remove support for `kubernetes-deploy.shopify.io` annotations

### ISSUE THREAD

**Issue by dturn** [Shopify/krane#526]
## Problem

We're transitioning from kubernetes-deploy to krane. This means that we need to stop supporting kubernetes-deploy.shopify.io annotations. This is the final step and should be done no sooner than the 1.0 release and it may be desirable to do this after the 1.0 release

## Possible solution
Remove all instances from the codebase. 

## Alternative solutions
Old annotations raise errors.

## Acceptance criteria
- `kubernetes-deploy.shopify.io` annotations no longer work.
- `krane.shopify.io` annotations continue to work.

## Additional context
https://github.com/Shopify/kubernetes-deploy/issues/256#issuecomment-475580770

**Comment by dturn** [comment]
We should stop annotating ejson secrets when we action this issue. The annotations aren't being used  by any code paths, though we should be sure to check with K8s#Krane to ensure external users aren't relying on it. 

This came up because in pre.1 the annotations still use the k8s-deploy prefix and that's causing the k8s-deploy annotation depreciations warning to trigger. This sucks since users can't fix it without going to 1.0, which is a managed env like ship-it is out of the user's control.

**Comment by KnVerey** [comment]
Is the warning about the ejson annotation we force actually fixed by moving 1.0? The annotation still uses `kubernetes-deploy` on master: https://github.com/Shopify/krane/blob/master/lib/krane/ejson_secret_provisioner.rb#L15

**Comment by airhorns** [comment]
Is it time for this maybe?

**Comment by dturn** [comment]
@airhorns the project is ready for it. Are you willing to PR it?

**Comment by xaviablaza** [comment]
Could we move forward with this deprecation with #587?

**Comment by dturn** [comment]
@xaviablaza Thanks for reminding us about this issue. We're ready to move forward, but it would be better if we handled all removing all of the old kubernetes-deploy annotations at once. Is that something you'd be willing to PR? If not even rebasing the PR you linked would be a big help. If you're unable we've got the work scheduled but I can't commit us to a definitive date.
