### ISSUE TITLE
secrets decrypting only works if krane is installed via bundler

### ISSUE THREAD

**Issue by tobsch** [Shopify/krane#643]
# Bug report

[Description of the bug]

**Expected behavior:**
One can install krane simply with "gem install krane" and it to deploy projects with a secrets.ejson.
All dependencies should be installed automatically. One does not need bundler and krane can be installed independent of ruby projects

**Actual behavior:** 
Secrets decoding only works if krane is installed via bundler. Otherwise the following error will pop deploy:
```
[FATAL][2019-11-21 16:51:15 +0000][gke_primeval-falcon-186518_europe-west3-a_omr][jobs-staging]	Generation of kubernetes secrets from ejson failed: failed to parse decrypted ejson
```

**Version(s) affected:** 1.0.0

any ideas why this could be the case?

**Comment by arenstar** [comment]
+1

**Comment by KnVerey** [comment]
Thanks for the bug report. The CLI is our primary interface, so agreed that what you're doing should absolutely work! 

1. Do you see ejson being installed when you `gem install krane`? ie.:

```
gem install krane                                                                                                                 
Fetching krane-1.0.0.gem
Fetching ejson-1.2.1.gem
Successfully installed ejson-1.2.1
Successfully installed krane-1.0.0
2 gems installed
```

2. Which platform are you on? 

3. The `ejson` gem actually installs an executable as well, and that executable must be in your path when you invoke `krane`. That should happen seamlessly, but perhaps this is where something is going wrong. Can you please confirm whether the `ejson` executable exists after installation, and whether it is available where you're invoking `krane`?

**Comment by tobsch** [comment]
Hi,

1. Yes, it is installed (```Successfully installed ejson-1.2.1```). It is also executable: ```ejson --version --> ejson version 1.2.1```

2. We use github actions to deploy (ubuntu-latest, ruby 2.6.x).

3. see 1, it is installed & executable and available. I guess we have to fork krane to make it more verbose and test?

**Comment by tobsch** [comment]
Okay, inspected it deeper: If I remove the catched exception it's easy to see: The result from shell execution does contain STDERR output which you try to parse:

```
/opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/gems/2.6.0/gems/tobsch-krane-1.0.1/lib/krane/ejson_secret_provisioner.rb:138:in `parse': Empty input () at line 1, column 2 [parse.c:979] in '/opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/gems/2.6.0/gems/ejson-1.2.1/bin/ejson:2: warning: Insecure world writable dir /opt/hostedtoolcache/Ruby/2.6.3/x64/bin in PATH, mode 040777 (JSON::ParserError)
60
{
61
  "_public_key": "c00238afc
```

**Comment by KnVerey** [comment]
Ok, I see what's going on. This should fix it: https://github.com/Shopify/krane/pull/647
