### ISSUE TITLE
Use Thor 1.0

### ISSUE THREAD

**Issue by timothysmith0609** [Shopify/krane#658]
### Why upgrade Thor?

The update to Thor contains 2 desirable changes:
__1.__ [Accept `-` as an argument, not a flag](https://github.com/erikhuda/thor/pull/691)
__2.__ [Allow options to be repeatable](https://github.com/erikhuda/thor/pull/674) __NOTE: This is dependent on [Thor#713](https://github.com/erikhuda/thor/pull/713)__

__1__ will allow us to deprecate the `--stdin` flag in favour of allowing `-` to be passed as an argument to `-f`
__2__ allows a closer semblance to `kubectl` semantics by allowing flags to be repeated in a given invocation

### TODO

- [x] Flesh out CLI tests

**Comment by dturn** [comment]
I believe it also addresses the issues raised in https://github.com/Shopify/krane/pull/559#issuecomment-561857195

**Comment by timothysmith0609** [comment]
Closed by #684

**Comment by timothysmith0609** [comment]
We have set the lower bar of Thor to 1.0, however we still need to add the repeatability of flags (as mentioned above, this is blocked on [Thor#713](https://github.com/erikhuda/thor/pull/674) __NOTE: This is dependent on [Thor#713](https://github.com/erikhuda/thor/pull/713)
