### ISSUE TITLE
Custom Resources often need secrets/config maps

### ISSUE THREAD

**Issue by benlangfeld** [Shopify/krane#670]
# Bug report

Krane deploys priority resources in an order that doesn't make sense, given that CRs are likely to depend on other resource types such as Secrets or RBAC resources in order to transition to Ready.

**Expected behavior:** Krane should not deploy CRs until after Secrets, ConfigMaps, etc. The only thing that needs to come after CRs is Pods.

**Actual behavior:** Krane deploys CRs before the things they quite possibly depend on.

**Version(s) affected:** 1.1.0

### Steps to Reproduce

1. Deploy templates which include a Secret and a CR (eg usage of the percona-operator).

**Comment by dturn** [comment]
This sounds reasonable, and will be a small code change (https://github.com/Shopify/krane/blob/master/lib/krane/deploy_task.rb#L60-L72). Any chance you've got time to PR something?

**Comment by benlangfeld** [comment]
@dturn Of course, I will gladly prepare a PR, just wanted to get in-principle approval first. Coming right up.
