### ISSUE TITLE
Server dry run sometimes fails without an error message

### ISSUE THREAD

**Issue by benlangfeld** [Shopify/krane#683]
# Bug report

Server dry run sometimes fails without an error message. I'm interested in knowing if anyone has any ideas why this might be. My only suspicion is the use of `--output=name`, but I have no evidence to support this.

**Expected behavior:**

Dry run validation should consistently pass or fail.

**Actual behavior:**

Sometimes I get an error like this one: https://gist.github.com/benlangfeld/8babdd217b9b216bc75a8f7eb278f813. There appears to be no pattern to it.

**Version(s) affected:**

v1.1.1

Since #570 

kubectl version:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

### Steps to Reproduce

Unsure

**Comment by benlangfeld** [comment]
I wonder if a change to ignore any dry-run failures with empty stdout would be accepted. This would allow deployments to progress to a point where maybe they'll succeed (if dry-run is being overzealous) or a real `apply` might provide a better error message.

**Comment by dturn** [comment]
We'd accept a PR that caused a server-dry-run failure with an empty *stderr* to fall back to non server dry run. A retry in that case could make sense too. Its probably worth it to confirm this isn't an issue in the versions of k8s you're running before PRing something.

**Comment by benlangfeld** [comment]
Empty server-dry-run stderr already falls back to client-side dry-run. In our case, client-side dry-run is also returning empty stderr (verified as precisely `""`), but that failure is caught. I havn't found anything that seems relevant in the kubernetes changelogs since v1.15.5. I'll propose on Monday a PR which considers empty stderr from client-side dry-run to be the absence of an error.
