### ISSUE TITLE
eJson and TLS certificate

### ISSUE THREAD

**Issue by zedtux** [Shopify/krane#686]
I'm using ejson in order to encrypt my secrets, and I'd like to import my CA crt and key so I tried to import them by copying/pasting the output of this:

```
cat ~/Downloads/ca.crt | tr -d '\n'
cat ~/Downloads/ca.key | tr -d '\n'
```

into the `secrets.ejson` but `cert-manager` is doing an error when I import my issuer.

Then I tried the "normal" way:

```
kubectl create secret tls ca-key-pair \
   --cert=ca.crt \
   --key=ca.key \
   --dry-run \
   --output=yaml
```

And I saw that the output is completely different and when I decode the base64 strings, I can see that the newline characters are present.

So I tried to copy/past directly the content without removing the newline characters but when I do `ejson encrypt ...` I got the error:

```
Encryption failed: invalid character '\n' in string literal
```

So I'd like to know how I can import my CA files via ejson?

**Comment by ryandv** [comment]
Would you be willing to provide the error given by `cert-manager` when using `secrets.ejson` to import the secrets into the cluster?

**Comment by zedtux** [comment]
The error I got is the following:

```
Error getting keypair for CA issuer: error decoding cert PEM block
```

**Comment by dturn** [comment]
@zedtux It sounds like you discovered you can't have line breaks in ejson. But what you can do is 

ca.crt:
```
abc
123
!@#
```

and write `ca.crt:  "abc\n123\n!@#"` into the ejson secret file and then encrypt that.

**Comment by zedtux** [comment]
> It sounds like you discovered you can't have line breaks in ejson.

Yeah ... Just to be sure: I was using `tr -d '\n'` in order to remove the line breaks and get a single line string, but whatever.

I will try that.

**Comment by dturn** [comment]
Great, feel free to reopen if this doesn't fix the problem.
