### ISSUE TITLE
Proposal: Add '--restart' flag to 'krane deploy' to restart the resource

### ISSUE THREAD

**Issue by aca** [Shopify/krane#708]
# Feature request

**Proposal:** Add '--restart' flag to ```krane deploy``` to restart the resource.

If resource definition is same, mostly when users use 'latest' docker tag, ```krane deploy``` command end immediately as nothing has changed. 

We have to run ```krane restart``` to force restart deployment and pull latest image.
It is obviously not a recommended way to deploy resource in ```latest``` tag. But It would be great if ```krane deploy``` could do the same thing  ```krane restart``` does, when "--restart" flag is given.

**Comment by dturn** [comment]
Hi @aca I'm going to reject this feature. Using the latest tag is an anit-pattern and its against our philosophy to make it easy (easier) to do the wrong thing.
