### ISSUE TITLE
Deploy in-cluster without kube config file

### ISSUE THREAD

**Issue by ppawiggers** [Shopify/krane#729]
# Feature request

**Proposal:**
We run a dozen of GKE Kubernetes clusters, all with a Gitlab Runner inside the cluster. This runner has the cluster-admin RBAC clusterrole and deploys resources in the cluster it's running in (triggered by a GitLab CI Pipeline). This way, the runner does not need any Kubernetes credentials. From the Gitlab Runner container, we can execute any `kubectl` command.

We want to use Krane for deployments, however Krane seems to require a kube config file and a kube context. I think this should in my case not be required - if not specified it should just assume `kubectl` already works as is.

My workaround currently is:
```
CLUSTER=$(gcloud container clusters list --format json --flatten name | jq -r ".[0]")
gcloud container clusters get-credentials ${CLUSTER} --zone=europe-west4-c
krane deploy mynamespace $(kubectl config current-context) -f k8s.yaml
```

But I think technically it could just be:
```
krane deploy mynamespace -f k8s.yaml
```

**Comment by dturn** [comment]
👋  Thanks for the issue. In the past we've talked about a config file that would allow people to specify defaults like cluster name or namespace. However, we haven't had the resources to build that idea out. Till then most of our users inovke the CLI from a shared environment where relying on the current conext would be very dangerous. 

As for not needing a kubeconfig file its true that `krane deploy` doesn't need one. But some of our other commands use `kubeclient` gem to talk to the clusters and that does require us discovering the server ip. I wasn't aware the kubectl could work without a kubeconfig file. Is `get-credentials` creating it for you or is there some other process going on?

**Comment by ppawiggers** [comment]
Yes, `get-credentials` is creating a `kubeconfig` file. However without it, `kubectl` also work because I run them from within the cluster itself. I don't know if this is a feature specific to GKE (and that they do some authentication and proxying under the hood).

I can image that if underlying libraries do need a `kubeconfig` file, this is difficult to implement. For now this workaround works fine for me (`get-credentials`); it would just have been nice if it was easily possible to make the `kubeconfig` argument in `krane` optional and it would work.

**Comment by dturn** [comment]
Sorry we weren't able to make the changes, but I did learn more about kube auth.
