### ISSUE TITLE
Unquoted strings not preserved by krane deploy

### ISSUE THREAD

**Issue by jpfourny** [Shopify/krane#736]
# Bug report

An env key-value pair like this:
```
- name: TEST_SHOP_IDS
  value: 1,1
```
is being rendered like this during deploy:
```
- name: TEST_SHOP_IDS
  value: 11
```

Note: Render command is fine - it seems to be lost explicitly during deploy command.

Although explicitly quoting "1,1" on input works around the issue, tools like `krate` will not emit explicit quotes unless required (and it is NOT required in this case by YAML spec). Krane needs to solve this issue.

**Note: This issue is blocking progress on the following items:**
* PR: https://github.com/Shopify/flow/pull/7571
* Migration: https://github.com/Shopify/app-lifecycle/issues/281

### Steps to Reproduce

1. Create a YAML file with a K8s Pod resource that includes an env like the one mentioned above (with unquote value `1,1`)
2. Execute krane render -f <file> | krane deploy default <context> 
3. Observe an error from K8 API server like "cannot convert int64 to string"

**Comment by timothysmith0609** [comment]
The `,` character is treated as a (european) number separator, and this is consistent behaviour with the ruby `yaml` library. This is analagous to the `true` (bool) vs `"true"` (string) problem that often crops up in YAML, as well.

You're right that the YAML spec does not explicitly mention this, but this seems to be the intended behaviour, at least for Psych, if not libyaml itself

**Comment by jpfourny** [comment]
I see your point, but I find it interesting that `1,1` became `11`. Should it not have become `1.1` in the output? Anyway, I may consider fixing this in krate somehow ...

**Comment by jpfourny** [comment]
@timothysmith0609  Even `0,0,0,0,0,0` -> `0` ... and that does not seem like a valid number. Seems a little loosey-goosey to me.

**Comment by jpfourny** [comment]
Anyway, I will compensate in krate. No worries.

**Comment by jugatsu** [comment]
Hey!

@jpfourny What do you mean by krate?

I have the same issue but with `50153e98` treated as E-notation (https://en.wikipedia.org/wiki/Scientific_notation#E_notation)

For example (any `\d+e\d+` string):

```yaml
- name: CACHE_PREFIX
   value: "50153e98"
```
after `krane deploy` becomes:

```yaml
- name: CACHE_VIEWS_PREFIX
   value: 50153e98
```

Guys, @jpfourny @timothysmith0609 how can i workaround this issue?

**Comment by jpfourny** [comment]
> Hey!
> 
> @jpfourny What do you mean by krate?
> 
> I have the same issue but with `50153e98` treated as E-notation (https://en.wikipedia.org/wiki/Scientific_notation#E_notation)
> 
> For example (any `\d+e\d+` string):
> 
> ```yaml
> - name: CACHE_PREFIX
>    value: "50153e98"
> ```
> 
> after `krane deploy` becomes:
> 
> ```yaml
> - name: CACHE_PREFIX
>    value: 50153e98
> ```
> 
> Guys, @jpfourny @timothysmith0609 how can i workaround this issue?

The e-notation problem is distinct from the comma-delimited case I hit. In any YAML 1.2 compliant parser, scientific notation is accepted with _optional_ decimal point and _optional_ +/- following 'e' or 'E'. This was to be on-par with what JSON allows. However, with Psych (YAML engine for Ruby), decimal point and +/- trailing 'e' is REQUIRED to be interpreted as a float. As a consequence, YAML serialization will forgoe the "" quotes around the scalar. Once this unecapsulated string makes it's way to kubectl (or any Go-based tool), it will be interpreted as a FLOAT. OOPS! 

Fun fact: Psych YAML interpretation of e-notation can differ between Linux and Darwin (Mac), depending on the `libyaml` version under the covers. It's a hot stinking mess....

I am not sure there is any magic workaround - it is going to be hacks galore to fix this. I am currently working on addressing this in krater, a tool to convert ERB-based deployments to runtime manifests, but it sounds like this exists in krane deploy codepath, too.

**Comment by jpfourny** [comment]
@jugatsu : Here is PR to workaround e-notation problem in `krater`: https://github.com/Shopify/krater/pull/183
Note: If `krane deploy` is having problems, we can try a similar hack.

**Comment by jugatsu** [comment]
@jpfourny thank you for your comment, I appreciate it. But I don't have access to krater repo )

**Comment by jpfourny** [comment]
> @jpfourny thank you for your comment, I appreciate it. But I don't have access to krater repo ) Can you share this code via gist?

I am currently refining things based on feedback. After I polish my changes, I will send you some code snippets.

**Comment by jpfourny** [comment]
@jugatsu I ended up with a monkey-patch to Psych to address the problem.

```
# frozen_string_literal: true

require 'psych'

# Monkey-patching Psych.dump with an alternative string serializer that tweaks scalar style for compatibility reasons.
module Psych
  class << self
    def dump(o, io = nil, options = {})
      if io.is_a?(Hash)
        options = io
        io = nil
      end

      visitor = Psych::Visitors::YAMLTree.create(options)
      visitor << o
      visitor.tree.each { |n| fix_node(n) }
      visitor.tree.yaml(io, options)
    end

    def fix_node(n)
      # String scalars that looks like e-notation floats must be quoted.
      if n.is_a?(Psych::Nodes::Scalar) &&
          (n.style == Psych::Nodes::Scalar::PLAIN) &&
          n.value.is_a?(String) &&
          n.value =~ /\A[+-]?\d+(?:\.\d+)?[eE][+-]?\d+\z/

        n.style = Psych::Nodes::Scalar::DOUBLE_QUOTED
      end
    end
  end
end
```

**Comment by jpfourny** [comment]
If you drop this into a Ruby file and include it, it should globally change the serialization to force double-quoting of any strings that resemble scientific notation. It would then be safe to consume by Go and K8s.

**Comment by jugatsu** [comment]
@jugatsu Great! Thanks a lot, i will try.
