### ISSUE TITLE
Only secrets are marked SERVER_DRY_RUNNABLE

### ISSUE THREAD

**Issue by timothysmith0609** [Shopify/krane#780]
# Bug report

During perf test of 1.18 clusters, we noticed a drop in performance in Phase 1. After looking closely, we noticed that only `Secret` resources were being dry-run server-side. Upon further investigation, `KubernetesResource`s are defaulted to `SERVER_DRY_RUNNABLE = false` and only `Secret` overrides this. At first blush, this seems like an oversight.

# TODO

- Investigate why only secrets are marked as server-side dry-runnable
- Expand list of server-side dry-runnable resources to encompass a more comprehensive list

**Comment by dturn** [comment]
From my memory (so its worth double checking) you can't server side dry run resources with dependencies individually . E.g. if a deployment mounts a volume server side dry run will reject it unless you dry-run deployment and the volume. So there are likely more resources we could add, but it might not be as helpful as we'd want.

**Comment by timothysmith0609** [comment]
#788 moved over to running batched server-side dry runs, obviating the need to specify per resource constraints. As of 2.1.4, we simply fallback to the prior behaviour (dry-run each resource individually). For now, there should be no more work to do here, though we could remove the SERVER_DRY_RUNNABLE constant if we determine it's unneeded.
