### ISSUE TITLE
krane 2.1.3 - no matches for kind "TCPIngress" in version "configuration.konghq.com/v1"

### ISSUE THREAD

**Issue by peter-dough** [Shopify/krane#785]
Deployments via `krane` fail when Kong API Gateway is deployed to the same GKE cluster. Please add an override for TCPIngress (eg. `"TCPIngress" => "v1beta1"`). As a reference, please see [#721](https://github.com/Shopify/krane/issues/721) as the issue is very similar.

**Sample Error**:
```
[FATAL][2021-01-19 13:03:01 -0800]	Unidentified error(s):
[FATAL][2021-01-19 13:03:01 -0800]	    error: no matches for kind "TCPIngress" in version "configuration.konghq.com/v1"
```

**Expected behavior:**
Successful Deployment

**Actual behavior:** 
Deployment fails

**Version(s) affected:**
2.1.3

### Steps to Reproduce

1. Deploy kong to gke cluster
2. Deploy app via krane
3. Deployment fails

**Comment by timothysmith0609** [comment]
Closed via #786
