### ISSUE TITLE
krane 2.1.4 / 2.1.5 - no matches for kind "WorkloadGroup" in version "networking.istio.io/v1beta1"

### ISSUE THREAD

**Issue by dan-leanix** [Shopify/krane#795]
Istio still does not have `WorkloadGroup` in the API version networking.istio.io/v1beta1. Therefore, we need an override for it like in #721 pointing `WorkloadGroup` to API version networking.istio.io/v1alpha3.

For reference, the Istio API version: https://github.com/istio/api/tree/master/networking/v1alpha3

```
[FATAL][2021-01-29 09:51:30 +0000]	Unidentified error(s):
[FATAL][2021-01-29 09:51:30 +0000]	    error: no matches for kind "WorkloadGroup" in version "networking.istio.io/v1beta1"
```

**Expected behavior:**
Successful Deployment

**Actual behavior:**
Deployment fails

**Version(s) affected:**
2.1.4 and 2.1.5

**Steps to Reproduce**

1. Setup Azure Kubernetes Service 1.18.10
2. Deploy Istio 1.8.2
3. Try deploying with krane to the cluster

**Comment by dturn** [comment]
Good news. We've merged https://github.com/Shopify/krane/pull/778 which in the real fix to this problem (and removes the need for an override list). We're planning to release a new version this week. Feel free to re-open this issue if you have any questions for problems.

**Comment by dan-leanix** [comment]
@dturn Great news. We will for sure test this when the new version is released and provide feedback.
