### ISSUE TITLE
Problem with pruning crds when multiple versions are available. e.g. monitoring.coreos.com/v1

### ISSUE THREAD

**Issue by larsdekroon** [Shopify/krane#799]
# Bug report

When I run krane on my cluster, it looks up all crd's so they can be pruned if they are not defined. However, alertsmanagersconfig is a crd which has an v1alpha version, but the prune-whitelist is assigned to monitoring.coreos.com/v1/alertsmanagersconfig. This fails, since only monitoring.coreos.com/v1alpha/alertsmanagersconfig exists. 

**Expected behavior:**
A correct combination of the crd's with the result from kubectl api-versions

**Actual behavior:** 
    error: no matches for kind "AlertmanagerConfig" in version "monitoring.coreos.com/v1"

**Version(s) affected:**
2.1.5 and before

### Steps to Reproduce

1. kubectl apply -f https://raw.githubusercontent.com/prometheus-community/helm-charts/main/charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml

2. kubectl apply -f https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml

3. krane deploy any resource

**Comment by dturn** [comment]
@larsdekroon Thanks for filing this bug. I think this is a new example of https://github.com/Shopify/krane/pull/696 /  https://github.com/Shopify/krane/issues/699. Can you confirm? I

**Comment by larsdekroon** [comment]
@dturn Yes! It seems like the same problem. #795 as well! I think you can get the correct version from "kubectl api-resources" and use that version!

**Comment by dturn** [comment]
Good news. We've merged https://github.com/Shopify/krane/pull/778 which in the real fix to this problem (and removes the need for an override list). We're planning to release a new version this week. Feel free to re-open this issue if you have any questions for problems.

**Comment by larsdekroon** [comment]
Thanks! Seems nice!
